# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.IntegerField()),
                ('fecha_lanzamiento', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField(null=True)),
                ('archivo_pdf', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('texto', models.TextField()),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Lee_libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminado', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('ISBN', models.IntegerField(unique=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to=b'')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('foto', models.FileField(null=True, upload_to=b'')),
                ('link', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Posee_trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_suscripcion', models.DateField()),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_tarjeta', models.CharField(max_length=18, unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('dni_titular', models.CharField(max_length=8)),
                ('empresa', models.CharField(max_length=254)),
                ('codigo_seguridad', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_maxima_perfiles', models.IntegerField(default=0)),
                ('tipo_suscripcion', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Completo',
            fields=[
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='modelos.Libro')),
                ('fecha_lanzamiento', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField(null=True)),
                ('archivo_pdf', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Incompleto',
            fields=[
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='modelos.Libro')),
            ],
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='nro_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Tarjeta'),
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='tipo_suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Tipo_Suscripcion'),
        ),
        migrations.AddField(
            model_name='posee_trailer',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro'),
        ),
        migrations.AddField(
            model_name='posee_trailer',
            name='trailer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelos.Trailer'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Suscriptor'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='listado_favoritos',
            field=models.ManyToManyField(to='modelos.Libro'),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='modelos.Autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='modelos.Editorial'),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='modelos.Genero'),
        ),
        migrations.AddField(
            model_name='lee_libro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro'),
        ),
        migrations.AddField(
            model_name='lee_libro',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Perfil'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='perfil',
            unique_together=set([('nombre_perfil', 'auth')]),
        ),
        migrations.AlterUniqueTogether(
            name='lee_libro',
            unique_together=set([('libro', 'perfil')]),
        ),
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together=set([('fecha_hora', 'calificacion')]),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro_Incompleto'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set([('libro', 'perfil')]),
        ),
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together=set([('capitulo', 'titulo')]),
        ),
    ]
