# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.IntegerField()),
                ('fecha_lanzamiento', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField(null=True)),
                ('archivo_pdf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('texto', models.TextField()),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('nombre', models.CharField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lee_libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminado', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('titulo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('foto', models.TextField(null=True)),
                ('audio', models.TextField(null=True)),
                ('video', models.TextField(null=True)),
                ('texto', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Posee_trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('fecha_vencimiento', models.DateField()),
                ('dni_titular', models.CharField(max_length=8)),
                ('empresa', models.CharField(max_length=254)),
                ('codigo_seguridad', models.CharField(max_length=3)),
                ('nro_tarjeta', models.CharField(max_length=18, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Suscripcion',
            fields=[
                ('cantidad_maxima_perfiles', models.IntegerField(default=0)),
                ('tipo_suscripcion', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('clave', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='modelos.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Completo',
            fields=[
                ('titulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='modelos.Libro')),
                ('fecha_lanzamiento', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField(null=True)),
                ('archivo_pdf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Incompleto',
            fields=[
                ('titulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='modelos.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='modelos.Usuario')),
                ('fecha_suscripcion', models.DateField()),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('nro_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Tarjeta')),
                ('tipo_suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Tipo_Suscripcion')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posee_trailer',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro'),
        ),
        migrations.AddField(
            model_name='posee_trailer',
            name='trailer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelos.Trailer'),
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='modelos.Autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(max_length=35, on_delete=django.db.models.deletion.CASCADE, to='modelos.Editorial'),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='modelos.Genero'),
        ),
        migrations.AddField(
            model_name='libro',
            name='listado_favoritos',
            field=models.ManyToManyField(to='modelos.Perfil'),
        ),
        migrations.AddField(
            model_name='lee_libro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro'),
        ),
        migrations.AddField(
            model_name='lee_libro',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Perfil'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Suscriptor'),
        ),
        migrations.AlterUniqueTogether(
            name='lee_libro',
            unique_together=set([('libro', 'perfil')]),
        ),
        migrations.AlterUniqueTogether(
            name='comentario',
            unique_together=set([('fecha_hora', 'calificacion')]),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro_Incompleto'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set([('libro', 'perfil')]),
        ),
        migrations.AlterUniqueTogether(
            name='perfil',
            unique_together=set([('nombre_perfil', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together=set([('capitulo', 'titulo')]),
        ),
    ]
