# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_auto_20200511_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
