# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20200513_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={'ordering': ['titulo'], 'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='foto',
        ),
        migrations.AddField(
            model_name='novedad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
