# Generated by Django 3.0.5 on 2020-05-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20200513_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='archivo_pdf',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='libro_completo',
            name='archivo_pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
