# Generated by Django 3.0.4 on 2020-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_auto_20200514_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='link',
        ),
        migrations.RemoveField(
            model_name='suscriptor',
            name='dni',
        ),
        migrations.AddField(
            model_name='novedad',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
