# Generated by Django 3.0.5 on 2020-05-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_auto_20200515_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='nro_tarjeta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelos.Tarjeta'),
        ),
    ]
