# Generated by Django 3.0.5 on 2020-06-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0009_auto_20200518_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trailer',
            options={'verbose_name': 'Trailer', 'verbose_name_plural': 'Trailers'},
        ),
        migrations.AddField(
            model_name='trailer',
            name='descripcion',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='trailer',
            name='libro_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='trailer',
            name='titulo',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='nro_tarjeta',
            field=models.CharField(max_length=16),
        ),
    ]
