# Generated by Django 3.0.5 on 2020-06-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0010_auto_20200606_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='libro_asociado',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='titulo',
        ),
    ]
