# Generated by Django 3.0.5 on 2020-06-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0011_auto_20200606_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='descripcion',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='trailer',
            name='libro_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelos.Libro'),
        ),
    ]
